name: Build, Link & Test

on:
  pull_request:
    branches:
      - 'main'

env:
  NEXT_PUBLIC_WEBSITE_DOMAIN: ''

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Cache node_modules
        id: node-modules-cached
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Dep install
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [install]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Cache node_modules
        id: node-modules-cached
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Cache node_modules
        id: node-modules-cached
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Build
        run: npm run build:static

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: static_web_build
          path: ./out
          if-no-files-found: error

  integration:
    runs-on: ubuntu-latest
    needs: [install, build]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Cache node_modules
        id: node-modules-cached
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: static_web_build
          path: ./out

      - name: Cypress run
        id: cypress
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          install: false
          start: npm run serve
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
