name: Build & Test

on:
  push:
    branches:
      - 'main'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NEXT_PUBLIC_WEBSITE_DOMAIN: ${{ secrets.WEBSITE_DOMAIN }}
  NEXT_PUBLIC_HTTPS: ${{ secrets.HTTPS }}
  NEXT_PUBLIC_IMAGE_LOADER_URL: ${{ secrets.IMAGE_LOADER_URL }}

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Cache node_modules
        id: node-modules-cached
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Dep install
        run: npm ci

  build:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Cache node_modules
        id: node-modules-cached
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Build
        run: npm run build:static

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: static_web_build
          path: ./out
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: [install, build]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Cache node_modules
        id: node-modules-cached
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: static_web_build
          path: ./out

      - name: CNAME Records
        run: echo "${{ secrets.WEBSITE_DOMAIN }}" >> ./out/CNAME

      - name: Deploy gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
