name: Build, Link & Test

on:
  pull_request:
    branches:
      - 'main'

env:
  NEXT_PUBLIC_WEBSITE_DOMAIN: ${{ secrets.WEBSITE_DOMAIN }}
  NEXT_PUBLIC_HTTPS: ${{ secrets.HTTPS }}
  NEXT_PUBLIC_IMAGE_LOADER_URL: ${{ secrets.IMAGE_LOADER_URL }}

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Cache node_modules
        id: node-modules-cached
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Dep install
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [install]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Cache node_modules
        id: node-modules-cached
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Cache node_modules
        id: node-modules-cached
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: web_build
          path: ./.next
          if-no-files-found: error

  integration:
    runs-on: ubuntu-latest
    needs: [install, build]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Cache node_modules
        id: node-modules-cached
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: web_build
          path: ./.next

      - name: Start
        run: npm run start

      - name: Cypress
        run: npm run cypress:ci
